source 'https://rubygems.org'

gem 'sinatra'

#Thin Webserver
gem 'thin'

#JSON
gem 'json', '~> 2.1'

gem 'nokogiri', '~> 1.6', '>= 1.6.6.2'

gem 'httparty'

gem 'pry', '~> 0.11.2'

group :development, :test do
    gem 'rack-test'
    gem 'test-unit'
end